<a href="https://colab.research.google.com/github/twronski/MLFreeCodeCamp/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Basic Tensors



In [ ]:
 import tensorflow as tf

## Zero Dimensional Tensor


In [ ]:
tensor_zero_d = tf.constant(44)
print(tensor_zero_d)
print(tensor_zero_d.shape)
print(tensor_zero_d.ndim)

tf.Tensor(44, shape=(), dtype=int32)
()
0


## One Dimensional Tensor

> Composed by several **zero** dimensional tensors

### Example A

In [ ]:
tensor_one_d_a = tf.constant([2,7,4,99])
print(tensor_one_d_a)
print(tensor_one_d_a.shape)
print(tensor_one_d_a.ndim)

tf.Tensor([ 2  7  4 99], shape=(4,), dtype=int32)
(4,)
1


### Example B (float)

In [ ]:
tensor_one_d_b = tf.constant([2.0 ,7,4,99])
print(tensor_one_d_b)
print(tensor_one_d_b.shape)
print(tensor_one_d_b.ndim)

tf.Tensor([ 2.  7.  4. 99.], shape=(4,), dtype=float32)
(4,)
1


## Two Dimensional Tensor

> Composed by several **one** dimensional tensors

### Example A

In [ ]:
tensor_two_d_a = tf.constant([[2,7,4,99]])
print(tensor_two_d_a)
print(tensor_two_d_a.shape)
print(tensor_two_d_a.ndim)

tf.Tensor([[ 2  7  4 99]], shape=(1, 4), dtype=int32)
(1, 4)
2


### Example B

In [ ]:
tensor_two_d_b = tf.constant([[2,7,4,99],
                              [34,12,-34,23]])
print(tensor_two_d_b)
print(tensor_two_d_b.shape)
print(tensor_two_d_b.ndim)


tf.Tensor(
[[  2   7   4  99]
 [ 34  12 -34  23]], shape=(2, 4), dtype=int32)
(2, 4)
2


## Three Dimensional Tensor

> Composed by several **two** dimensional tensors

### Example A

> If I change one number to float, the whole tensor becomes float

In [ ]:
tensor_three_d_a = tf.constant([[[2,7,4,99.6],
                              [34,12,-34,23]],
                                [[2,7,4,-99],
                              [44,12,-34,25673]]
                                ])
print(tensor_three_d_a)
print(tensor_three_d_a.shape)
print(tensor_three_d_a.ndim)


tf.Tensor(
[[[ 2.0000e+00  7.0000e+00  4.0000e+00  9.9600e+01]
  [ 3.4000e+01  1.2000e+01 -3.4000e+01  2.3000e+01]]

 [[ 2.0000e+00  7.0000e+00  4.0000e+00 -9.9000e+01]
  [ 4.4000e+01  1.2000e+01 -3.4000e+01  2.5673e+04]]], shape=(2, 2, 4), dtype=float32)
(2, 2, 4)
3


## Four Dimensional Tensor

> Composed by several **three** dimensional tensors

### Example A

In [ ]:
tensor_four_d_a = tf.constant(
    [
     [
      [[1,2,3],
       [12, -4, 390]],
      [[1,2,3],
       [12, -4, 390]]
     ],

     [
      [[1,2,3],
       [12, -4, 390]],
      [[1,2,3],
       [12, -4, 390]]
     ]

    ]
    )

print(tensor_four_d_a)
print(tensor_four_d_a.shape)
print(tensor_four_d_a.ndim)


tf.Tensor(
[[[[  1   2   3]
   [ 12  -4 390]]

  [[  1   2   3]
   [ 12  -4 390]]]


 [[[  1   2   3]
   [ 12  -4 390]]

  [[  1   2   3]
   [ 12  -4 390]]]], shape=(2, 2, 2, 3), dtype=int32)
(2, 2, 2, 3)
4


## TF Convert nunpy arrays

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([[1,2,7],
                    [12,3,40]])
print(np_array)

tf_converted_array = tf.convert_to_tensor(np_array)
print(tf_converted_array)

[[ 1  2  7]
 [12  3 40]]
tf.Tensor(
[[ 1  2  7]
 [12  3 40]], shape=(2, 3), dtype=int64)


## TF Eye Method

### Example A


In [ ]:
identity_matrix_a = tf.eye(3, dtype=tf.bool)
print(identity_matrix_a)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


## TF Fill Method

### Example A - Two Dimensions

In [ ]:
fill_tensor_a = tf.fill([2,7], 10)
print(fill_tensor_a)

## TF Fill Method

### Example B - Four Dimensions and Using tf.size Method

In [ ]:
fill_tensor_b = tf.fill([2,7,9,4], 10)
print(fill_tensor_b)
tf.size(fill_tensor_b)

tf.Tensor(
[[[[10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]]

  [[10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]]

  [[10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]]

  [[10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]]

  [[10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]]

  [[10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]]

  [[10 10 10 10]
   [10 10 10 10]
   [10 10 10 10]
   [10 1

<tf.Tensor: shape=(), dtype=int32, numpy=504>

## tf.ones()

## tf.like_ones()

## tf.rank()

## tf.size()